export const COMMANDS = [
  { id:'info',        name:'info',         icon:'🔍', cat:'Profile',    desc:'Retrieve full account info: bio, followers count, post count, and verification status.' },
  { id:'propic',      name:'propic',       icon:'🖼️', cat:'Profile',    desc:'Download the target\'s profile picture at full resolution.' },
  { id:'followers',   name:'followers',    icon:'👥', cat:'Social',     desc:'List all followers of the target account with usernames and IDs.' },
  { id:'followings',  name:'followings',   icon:'🔗', cat:'Social',     desc:'List all accounts that the target is following.' },
  { id:'tagged',      name:'tagged',       icon:'🏷️', cat:'Social',     desc:'Get a list of users who were tagged by the target in their posts.' },
  { id:'wtagged',     name:'wtagged',      icon:'📌', cat:'Social',     desc:'Get a list of users who tagged the target in their posts.' },
  { id:'wcommented',  name:'wcommented',   icon:'💬', cat:'Social',     desc:'Get a list of users who commented on the target\'s posts.' },
  { id:'photos',      name:'photos',       icon:'📸', cat:'Content',    desc:'Download all public photos posted by the target to an output folder.' },
  { id:'stories',     name:'stories',      icon:'🎞️', cat:'Content',    desc:'Download the target\'s currently active stories.' },
  { id:'metadata',    name:'metadata',     icon:'🧬', cat:'Content',    desc:'Fetch structured JSON metadata for media, including EXIF-like fields when available.' },
  { id:'locations',   name:'locations',    icon:'🗺️', cat:'Content',    desc:'Extract structured location coordinates and place metadata from available posts or stories.' },
  { id:'captions',    name:'captions',     icon:'✍️', cat:'Content',    desc:'Collect captions from all of the target\'s posts.' },
  { id:'photodes',    name:'photodes',     icon:'🗒️', cat:'Content',    desc:'Get the descriptions and alt-text of the target\'s photos.' },
  { id:'mediatype',   name:'mediatype',    icon:'🎬', cat:'Content',    desc:'Classify each post as a photo or video.' },
  { id:'hashtags',    name:'hashtags',     icon:'#️⃣', cat:'Content',    desc:'Extract and count all hashtags used by the target.' },
  { id:'likes',       name:'likes',        icon:'❤️', cat:'Engagement', desc:'Get total likes across all of the target\'s posts.' },
  { id:'comments',    name:'comments',     icon:'💭', cat:'Engagement', desc:'Get total comments across all of the target\'s posts.' },
  { id:'addrs',       name:'addrs',        icon:'📍', cat:'Contact',    desc:'Collect all registered addresses found in target\'s photo metadata.' },
  { id:'fwersemail',  name:'fwersemail',   icon:'📧', cat:'Contact',    desc:'Scrape email addresses from the target\'s followers.' },
  { id:'fwingsemail', name:'fwingsemail',  icon:'📨', cat:'Contact',    desc:'Scrape email addresses from accounts the target follows.' },
  { id:'fwersnumber', name:'fwersnumber',  icon:'📞', cat:'Contact',    desc:'Extract phone numbers from the target\'s followers.' },
  { id:'fwingsnumber',name:'fwingsnumber', icon:'☎️', cat:'Contact',    desc:'Extract phone numbers from accounts the target follows.' },
];
